source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PUStaticDataSource_Example', :exclusive => true do
  pod 'PUStaticDataSource', :path => '../'
end

target 'PUStaticDataSource_Tests', :exclusive => true do
  pod 'PUStaticDataSource', :path => '../'

  
end
